# -*- coding: utf-8 -*-
"""Task 3: Energy Consumption Time Series Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUGb6-6BivBTH6zSm5wZzMPF1ZG5_Pwy
"""

"""
Energy Consumption Time Series Forecasting
Dataset: UCI Household Power Consumption
Download: https://archive.ics.uci.edu/ml/datasets/individual+household+electric+power+consumption
File: household_power_consumption.txt (semicolon-separated)
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.gridspec import GridSpec
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

# 1. INSTALL CHECK
try:
    from statsmodels.tsa.arima.model import ARIMA
except ImportError:
    raise ImportError("Run: pip install statsmodels")

try:
    from prophet import Prophet
except ImportError:
    raise ImportError("Run: pip install prophet")

try:
    import xgboost as xgb
except ImportError:
    raise ImportError("Run: pip install xgboost")

# SECTION 1 ─ LOAD & PARSE DATA

def load_data(filepath: str = "household_power_consumption.txt") -> pd.DataFrame:
    """
    Load the UCI Household Power Consumption dataset.
    Falls back to synthetic data if the file is not found.
    """
    try:
        df = pd.read_csv(
            filepath,
            sep=";",
            parse_dates={"datetime": ["Date", "Time"]},
            dayfirst=True,
            na_values=["?"],
            low_memory=False,
        )
        df.set_index("datetime", inplace=True)
        df = df[["Global_active_power"]].dropna()
        df.columns = ["power"]
        df["power"] = pd.to_numeric(df["power"])
        print(f"✔  Loaded real dataset: {len(df):,} rows  ({df.index.min()} → {df.index.max()})")
        return df

    except FileNotFoundError:
        print("⚠  Dataset file not found – generating synthetic data for demonstration.\n"
              "   Download the real dataset from:\n"
              "   https://archive.ics.uci.edu/ml/datasets/individual+household+electric+power+consumption\n"
              "   and place 'household_power_consumption.txt' in the working directory.")
        return _make_synthetic()


def _make_synthetic(days: int = 90) -> pd.DataFrame:
    """Synthetic 1-minute household power with realistic daily/weekly cycles."""
    rng = pd.date_range("2023-01-01", periods=days * 24 * 60, freq="1min")
    hour   = rng.hour + rng.minute / 60
    dow    = rng.dayofweek

    daily   = 1.2 * np.sin(2 * np.pi * (hour - 6) / 24) + 1.5
    weekend = np.where(dow >= 5, 0.3, 0.0)
    noise   = np.random.normal(0, 0.15, len(rng))
    power   = np.clip(daily + weekend + noise, 0.05, None)

    return pd.DataFrame({"power": power}, index=rng)

# SECTION 2 ─ RESAMPLE & FEATURE ENGINEERING

def resample_hourly(df: pd.DataFrame) -> pd.DataFrame:
    """Resample minute-level data to hourly means."""
    hourly = df["power"].resample("1h").mean().dropna()
    return hourly.to_frame(name="power")


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add time-based features for ML model."""
    out = df.copy()
    out["hour"]       = out.index.hour
    out["dayofweek"]  = out.index.dayofweek
    out["month"]      = out.index.month
    out["is_weekend"] = (out.index.dayofweek >= 5).astype(int)
    out["hour_sin"]   = np.sin(2 * np.pi * out["hour"] / 24)
    out["hour_cos"]   = np.cos(2 * np.pi * out["hour"] / 24)
    out["dow_sin"]    = np.sin(2 * np.pi * out["dayofweek"] / 7)
    out["dow_cos"]    = np.cos(2 * np.pi * out["dayofweek"] / 7)

    # Lag features
    for lag in [1, 2, 3, 24, 48]:
        out[f"lag_{lag}"] = out["power"].shift(lag)

    # Rolling statistics
    out["rolling_mean_6h"]  = out["power"].shift(1).rolling(6).mean()
    out["rolling_mean_24h"] = out["power"].shift(1).rolling(24).mean()
    out["rolling_std_24h"]  = out["power"].shift(1).rolling(24).std()

    return out.dropna()


def train_test_split(df: pd.DataFrame, test_hours: int = 168):
    """Last `test_hours` hours as test set (default = 7 days)."""
    train = df.iloc[:-test_hours]
    test  = df.iloc[-test_hours:]
    return train, test

# SECTION 3 ─ MODEL: ARIMA
def run_arima(train: pd.DataFrame, test: pd.DataFrame) -> np.ndarray:
    """Fit ARIMA(2,1,2) on training data; forecast over test horizon."""
    print("  Fitting ARIMA …", end=" ", flush=True)
    model = ARIMA(train["power"], order=(2, 1, 2))
    fit   = model.fit()
    fc    = fit.forecast(steps=len(test))
    preds = np.clip(np.array(fc), 0, None)
    print("done")
    return preds

# SECTION 4 ─ MODEL: PROPHET

def run_prophet(train: pd.DataFrame, test: pd.DataFrame) -> np.ndarray:
    """Fit Facebook/Meta Prophet with daily + weekly seasonality."""
    print("  Fitting Prophet …", end=" ", flush=True)

    prophet_df = train[["power"]].reset_index()
    prophet_df.columns = ["ds", "y"]

    m = Prophet(
        yearly_seasonality=False,
        weekly_seasonality=True,
        daily_seasonality=True,
        changepoint_prior_scale=0.1,
    )
    m.fit(prophet_df)

    future = pd.DataFrame({"ds": test.index})
    fc     = m.predict(future)
    preds  = np.clip(fc["yhat"].values, 0, None)
    print("done")
    return preds

# SECTION 5 ─ MODEL: XGBOOST

FEATURE_COLS = [
    "hour", "dayofweek", "month", "is_weekend",
    "hour_sin", "hour_cos", "dow_sin", "dow_cos",
    "lag_1", "lag_2", "lag_3", "lag_24", "lag_48",
    "rolling_mean_6h", "rolling_mean_24h", "rolling_std_24h",
]


def run_xgboost(train: pd.DataFrame, test: pd.DataFrame) -> np.ndarray:
    """Train XGBoost regressor on engineered features."""
    print("  Fitting XGBoost …", end=" ", flush=True)

    X_train = train[FEATURE_COLS]
    y_train = train["power"]
    X_test  = test[FEATURE_COLS]

    model = xgb.XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        verbosity=0,
    )
    model.fit(X_train, y_train, eval_set=[(X_test, test["power"])], verbose=False)
    preds = np.clip(model.predict(X_test), 0, None)
    print("done")
    return preds, model

# SECTION 6 ─ EVALUATION

def evaluate(actual: np.ndarray, predicted: np.ndarray, name: str) -> dict:
    mae  = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    mape = np.mean(np.abs((actual - predicted) / (actual + 1e-8))) * 100
    print(f"    {name:<10}  MAE={mae:.4f}  RMSE={rmse:.4f}  MAPE={mape:.2f}%")
    return {"model": name, "MAE": mae, "RMSE": rmse, "MAPE": mape}

# SECTION 7 ─ VISUALISATION

COLORS = {
    "Actual":   "#1f77b4",
    "ARIMA":    "#e74c3c",
    "Prophet":  "#2ecc71",
    "XGBoost":  "#f39c12",
}


def plot_results(
    test: pd.DataFrame,
    preds: dict,
    metrics: list,
    train: pd.DataFrame,
):
    fig = plt.figure(figsize=(18, 14))
    fig.patch.set_facecolor("#0f1117")
    gs  = GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.3)

    ax_main  = fig.add_subplot(gs[0, :])
    ax_arima = fig.add_subplot(gs[1, 0])
    ax_proph = fig.add_subplot(gs[1, 1])
    ax_xgb   = fig.add_subplot(gs[2, 0])
    ax_bar   = fig.add_subplot(gs[2, 1])

    actual = test["power"].values
    ts     = test.index

    # Main overlay
    ax_main.plot(ts, actual, color=COLORS["Actual"], lw=1.5, label="Actual", zorder=5)
    for name, pred in preds.items():
        ax_main.plot(ts, pred, color=COLORS[name], lw=1.2, alpha=0.85, label=name)

    ax_main.set_title("All Models vs Actual – 7-Day Forecast", color="white", fontsize=13, pad=10)
    ax_main.legend(facecolor="#1c1f26", labelcolor="white", fontsize=9)
    ax_main.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    _style_ax(ax_main)

    # Per-model detail
    for ax, (name, pred) in zip([ax_arima, ax_proph, ax_xgb], preds.items()):
        ax.plot(ts, actual, color=COLORS["Actual"], lw=1.2, label="Actual")
        ax.plot(ts, pred,   color=COLORS[name],     lw=1.2, label=name, alpha=0.9)
        ax.fill_between(ts, actual, pred, alpha=0.15, color=COLORS[name])
        ax.set_title(name, color="white", fontsize=11)
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
        ax.legend(facecolor="#1c1f26", labelcolor="white", fontsize=8)
        _style_ax(ax)

    # Metric bar chart
    m_df  = pd.DataFrame(metrics).set_index("model")
    x     = np.arange(len(m_df))
    width = 0.25

    for i, metric in enumerate(["MAE", "RMSE", "MAPE"]):
        bars = ax_bar.bar(
            x + i * width,
            m_df[metric],
            width,
            label=metric,
            color=["#e74c3c", "#2ecc71", "#f39c12"][i],
            alpha=0.85,
        )
        for bar in bars:
            h = bar.get_height()
            ax_bar.text(
                bar.get_x() + bar.get_width() / 2,
                h + 0.005,
                f"{h:.3f}",
                ha="center", va="bottom",
                color="white", fontsize=7,
            )

    ax_bar.set_xticks(x + width)
    ax_bar.set_xticklabels(m_df.index, color="white", fontsize=9)
    ax_bar.set_title("Model Comparison (lower = better)", color="white", fontsize=11)
    ax_bar.legend(facecolor="#1c1f26", labelcolor="white", fontsize=8)
    _style_ax(ax_bar)

    fig.suptitle(
        "Household Energy Consumption Forecasting",
        color="white", fontsize=16, fontweight="bold", y=0.98,
    )
    plt.savefig("energy_forecast_results.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print("\n✔  Plot saved → energy_forecast_results.png")


def _style_ax(ax):
    ax.set_facecolor("#1c1f26")
    ax.tick_params(colors="white", labelsize=8)
    for spine in ax.spines.values():
        spine.set_edgecolor("#3a3f4b")
    ax.yaxis.label.set_color("white")
    ax.xaxis.label.set_color("white")
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")

# SECTION 8 ─ FEATURE IMPORTANCE (XGBoost)

def plot_feature_importance(model, top_n: int = 12):
    fi = (
        pd.Series(model.get_booster().get_fscore())
        .sort_values(ascending=True)
        .tail(top_n)
    )
    fig, ax = plt.subplots(figsize=(9, 5))
    fig.patch.set_facecolor("#0f1117")
    bars = ax.barh(fi.index, fi.values, color="#f39c12", alpha=0.85)
    ax.set_title(f"XGBoost – Top {top_n} Feature Importances",
                 color="white", fontsize=12, pad=10)
    _style_ax(ax)
    plt.tight_layout()
    plt.savefig("xgboost_feature_importance.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print("✔  Feature importance plot saved → xgboost_feature_importance.png")

# MAIN

def main():
    print("\n" + "═" * 60)
    print("  ENERGY CONSUMPTION FORECASTING PIPELINE")
    print("═" * 60)

    # 1. Load
    print("\n[1/5] Loading data …")
    raw     = load_data("household_power_consumption.txt")

    # 2. Resample & feature engineering
    print("[2/5] Resampling to hourly & engineering features …")
    hourly  = resample_hourly(raw)
    featured = engineer_features(hourly)
    print(f"      Hourly rows: {len(featured):,}  |  Features: {len(FEATURE_COLS)}")

    # 3. Split
    TEST_HOURS = 168  # 7 days
    train, test = train_test_split(featured, test_hours=TEST_HOURS)
    print(f"      Train: {len(train):,} h  |  Test: {len(test):,} h (7 days)")

    # 4. Models
    print("\n[3/5] Training models …")
    arima_preds          = run_arima(train, test)
    prophet_preds        = run_prophet(train, test)
    xgboost_preds, xg_m  = run_xgboost(train, test)

    # 5. Evaluate
    print("\n[4/5] Evaluation metrics …")
    actual  = test["power"].values
    metrics = [
        evaluate(actual, arima_preds,   "ARIMA"),
        evaluate(actual, prophet_preds, "Prophet"),
        evaluate(actual, xgboost_preds, "XGBoost"),
    ]

    # 6. Visualise
    print("\n[5/5] Plotting results …")
    preds = {
        "ARIMA":   arima_preds,
        "Prophet": prophet_preds,
        "XGBoost": xgboost_preds,
    }
    plot_results(test, preds, metrics, train)
    plot_feature_importance(xg_m)

    # 7. Summary table
    print("\n" + "═" * 60)
    print("  FINAL LEADERBOARD")
    print("═" * 60)
    df_m = pd.DataFrame(metrics).set_index("model").sort_values("RMSE")
    print(df_m.to_string(float_format="{:.4f}".format))
    best = df_m.index[0]
    print(f"\n  🏆  Best model by RMSE: {best}")
    print("═" * 60 + "\n")


if __name__ == "__main__":
    main()